# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-18 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.model_functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('movement', models.DecimalField(decimal_places=0, max_digits=1)),
                ('melee', models.DecimalField(decimal_places=0, max_digits=1)),
                ('ballistic', models.DecimalField(decimal_places=0, max_digits=1)),
                ('strength', models.DecimalField(decimal_places=0, max_digits=1)),
                ('toughness', models.DecimalField(decimal_places=0, max_digits=1)),
                ('wounds', models.DecimalField(decimal_places=0, max_digits=1)),
                ('initiative', models.DecimalField(decimal_places=0, max_digits=1)),
                ('attacks', models.DecimalField(decimal_places=0, max_digits=1)),
                ('moral', models.DecimalField(decimal_places=0, max_digits=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.Account')),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Faction')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.Account')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, utils.model_functions.DetailURLMixin),
        ),
    ]
