# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-19 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active_for_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
